variable "node_prefix" {}
variable "node_type" {}
variable "node_service" {}
variable "node_count" {}
variable "node_role" {}
variable "node_username" {}
variable "environment_id" {}
variable "network_id" {}
variable "ssh_key_name" {}
variable "cloudinit_data" {}
